// Seed data untuk Achievements Collection
export const achievementsSeedData = [
  // Vocabulary Achievements
  {
    title: 'First Steps',
    description: 'Learn your first 5 words',
    category: 'vocabulary',
    difficulty: 'bronze',
    icon: 'BookOpen',
    color: '#CD7F32',
    requirements: {
      type: 'words_learned',
      target: 5,
    },
    rewards: {
      experiencePoints: 50,
      title: 'Word Explorer',
    },
    isActive: true,
    isHidden: false,
    order: 1,
  },
  {
    title: 'Vocabulary Builder',
    description: 'Learn 25 new words',
    category: 'vocabulary',
    difficulty: 'silver',
    icon: 'BookOpen',
    color: '#C0C0C0',
    requirements: {
      type: 'words_learned',
      target: 25,
    },
    rewards: {
      experiencePoints: 150,
      title: 'Word Collector',
    },
    isActive: true,
    isHidden: false,
    order: 2,
  },
  {
    title: 'Word Master',
    description: 'Learn 100 new words',
    category: 'vocabulary',
    difficulty: 'gold',
    icon: 'Crown',
    color: '#FFD700',
    requirements: {
      type: 'words_learned',
      target: 100,
    },
    rewards: {
      experiencePoints: 500,
      title: 'Vocabulary Master',
    },
    isActive: true,
    isHidden: false,
    order: 3,
  },
  {
    title: 'Lexicon Legend',
    description: 'Learn 500 new words',
    category: 'vocabulary',
    difficulty: 'platinum',
    icon: 'Trophy',
    color: '#E5E4E2',
    requirements: {
      type: 'words_learned',
      target: 500,
    },
    rewards: {
      experiencePoints: 2000,
      title: 'Lexicon Legend',
      specialFeature: 'Advanced vocabulary insights',
    },
    isActive: true,
    isHidden: false,
    order: 4,
  },

  // Translation Achievements
  {
    title: 'Translation Rookie',
    description: 'Complete your first 10 translations',
    category: 'translation',
    difficulty: 'bronze',
    icon: 'Languages',
    color: '#CD7F32',
    requirements: {
      type: 'translations_count',
      target: 10,
    },
    rewards: {
      experiencePoints: 75,
      title: 'Translator',
    },
    isActive: true,
    isHidden: false,
    order: 5,
  },
  {
    title: 'Translation Pro',
    description: 'Complete 100 translations',
    category: 'translation',
    difficulty: 'silver',
    icon: 'Languages',
    color: '#C0C0C0',
    requirements: {
      type: 'translations_count',
      target: 100,
    },
    rewards: {
      experiencePoints: 300,
      title: 'Translation Pro',
    },
    isActive: true,
    isHidden: false,
    order: 6,
  },
  {
    title: 'Translation Expert',
    description: 'Complete 500 translations',
    category: 'translation',
    difficulty: 'gold',
    icon: 'Award',
    color: '#FFD700',
    requirements: {
      type: 'translations_count',
      target: 500,
    },
    rewards: {
      experiencePoints: 1000,
      title: 'Translation Expert',
    },
    isActive: true,
    isHidden: false,
    order: 7,
  },

  // Streak Achievements
  {
    title: 'Getting Started',
    description: 'Maintain a 3-day learning streak',
    category: 'streak',
    difficulty: 'bronze',
    icon: 'Flame',
    color: '#CD7F32',
    requirements: {
      type: 'streak_days',
      target: 3,
    },
    rewards: {
      experiencePoints: 100,
      title: 'Consistent Learner',
    },
    isActive: true,
    isHidden: false,
    order: 8,
  },
  {
    title: 'Week Warrior',
    description: 'Maintain a 7-day learning streak',
    category: 'streak',
    difficulty: 'silver',
    icon: 'Flame',
    color: '#C0C0C0',
    requirements: {
      type: 'streak_days',
      target: 7,
    },
    rewards: {
      experiencePoints: 250,
      title: 'Week Warrior',
    },
    isActive: true,
    isHidden: false,
    order: 9,
  },
  {
    title: 'Month Master',
    description: 'Maintain a 30-day learning streak',
    category: 'streak',
    difficulty: 'gold',
    icon: 'Calendar',
    color: '#FFD700',
    requirements: {
      type: 'streak_days',
      target: 30,
    },
    rewards: {
      experiencePoints: 1000,
      title: 'Dedication Master',
      specialFeature: 'Streak protection (1 free miss)',
    },
    isActive: true,
    isHidden: false,
    order: 10,
  },
  {
    title: 'Unstoppable',
    description: 'Maintain a 100-day learning streak',
    category: 'streak',
    difficulty: 'diamond',
    icon: 'Zap',
    color: '#B9F2FF',
    requirements: {
      type: 'streak_days',
      target: 100,
    },
    rewards: {
      experiencePoints: 5000,
      title: 'Unstoppable Force',
      specialFeature: 'Premium streak features',
    },
    isActive: true,
    isHidden: false,
    order: 11,
  },

  // Accuracy Achievements
  {
    title: 'Sharp Shooter',
    description: 'Achieve 90% accuracy on 20 translations',
    category: 'accuracy',
    difficulty: 'silver',
    icon: 'Target',
    color: '#C0C0C0',
    requirements: {
      type: 'accuracy_percentage',
      target: 90,
    },
    rewards: {
      experiencePoints: 200,
      title: 'Precision Expert',
    },
    isActive: true,
    isHidden: false,
    order: 12,
  },
  {
    title: 'Perfectionist',
    description: 'Achieve 95% accuracy on 50 translations',
    category: 'accuracy',
    difficulty: 'gold',
    icon: 'Star',
    color: '#FFD700',
    requirements: {
      type: 'accuracy_percentage',
      target: 95,
    },
    rewards: {
      experiencePoints: 750,
      title: 'Perfectionist',
    },
    isActive: true,
    isHidden: false,
    order: 13,
  },

  // Study Time Achievements
  {
    title: 'Study Buddy',
    description: 'Study for 10 hours total',
    category: 'study-time',
    difficulty: 'bronze',
    icon: 'Clock',
    color: '#CD7F32',
    requirements: {
      type: 'study_time_hours',
      target: 10,
    },
    rewards: {
      experiencePoints: 150,
      title: 'Study Buddy',
    },
    isActive: true,
    isHidden: false,
    order: 14,
  },
  {
    title: 'Dedicated Student',
    description: 'Study for 50 hours total',
    category: 'study-time',
    difficulty: 'silver',
    icon: 'Clock',
    color: '#C0C0C0',
    requirements: {
      type: 'study_time_hours',
      target: 50,
    },
    rewards: {
      experiencePoints: 500,
      title: 'Dedicated Student',
    },
    isActive: true,
    isHidden: false,
    order: 15,
  },

  // Goals Achievements
  {
    title: 'Goal Getter',
    description: 'Complete your first learning goal',
    category: 'goals',
    difficulty: 'bronze',
    icon: 'CheckCircle',
    color: '#CD7F32',
    requirements: {
      type: 'goals_completed',
      target: 1,
    },
    rewards: {
      experiencePoints: 100,
      title: 'Goal Getter',
    },
    isActive: true,
    isHidden: false,
    order: 16,
  },
  {
    title: 'Achievement Hunter',
    description: 'Complete 10 learning goals',
    category: 'goals',
    difficulty: 'gold',
    icon: 'Trophy',
    color: '#FFD700',
    requirements: {
      type: 'goals_completed',
      target: 10,
    },
    rewards: {
      experiencePoints: 1000,
      title: 'Achievement Hunter',
    },
    isActive: true,
    isHidden: false,
    order: 17,
  },

  // Special Achievements
  {
    title: 'Early Adopter',
    description: 'Join AskVerba in its early days',
    category: 'special',
    difficulty: 'platinum',
    icon: 'Sparkles',
    color: '#E5E4E2',
    requirements: {
      type: 'custom',
      target: 1,
      customCondition: JSON.stringify({
        condition: 'registration_before',
        date: '2024-12-31',
      }),
    },
    rewards: {
      experiencePoints: 500,
      title: 'Early Adopter',
      specialFeature: 'Exclusive early adopter badge',
    },
    isActive: true,
    isHidden: true,
    order: 18,
  },
  {
    title: 'Community Builder',
    description: 'Help improve AskVerba by providing feedback',
    category: 'special',
    difficulty: 'gold',
    icon: 'Users',
    color: '#FFD700',
    requirements: {
      type: 'custom',
      target: 1,
      customCondition: JSON.stringify({
        condition: 'feedback_submitted',
        count: 5,
      }),
    },
    rewards: {
      experiencePoints: 300,
      title: 'Community Builder',
    },
    isActive: true,
    isHidden: true,
    order: 19,
  },
]
